// Café coordinates [lat, lng] keyed by shop id. Generated by geocode.js / import-cafes.js.
export const coords = {
  "081": [
    52.3716265,
    4.930364099999999
  ],
  "30ml-coffee-food-westerpark": [
    52.389241399999996,
    4.8799385
  ],
  "5-coffee-connect": [
    52.3714861,
    4.8021601
  ],
  "7eventyfive": [
    52.392929599999995,
    4.8821186
  ],
  "a-sentimento-italian-gastronomy-pizzeria": [
    52.3824299,
    4.878508
  ],
  "a-van-wees-tasting-locality": [
    52.369967700000004,
    4.8872316
  ],
  "abraxas": [
    52.3721009,
    4.8912195999999994
  ],
  "al-ponte-caffe-italiano": [
    52.38189920000001,
    4.908176999999999
  ],
  "alpha-coffee-amsterdam": [
    52.3662631,
    4.9018763
  ],
  "amnesia-cannabis-thc-dispensary": [
    52.3755356,
    4.8890924
  ],
  "amstelcampus-cafe": [
    52.3584505,
    4.9101783
  ],
  "amsterdam-baking-company": [
    52.3496179,
    4.938642199999999
  ],
  "anne-max-amsterdam-oostenburg": [
    52.368953499999996,
    4.9220075
  ],
  "anne-max-amsterdam-zeeburg": [
    52.3745815,
    4.9351804
  ],
  "anne-max-amsterdam-zuid": [
    52.3518944,
    4.8561119999999995
  ],
  "anook-bakehouse": [
    52.351248,
    4.891265
  ],
  "arket-cafe": [
    52.3670487,
    4.8885575999999995
  ],
  "arte-vanilla": [
    52.364601199999996,
    4.861250500000001
  ],
  "artsy-avenue": [
    52.366358,
    4.8770229
  ],
  "ashes-to-snow": [
    52.363492099999995,
    4.926199
  ],
  "at-the-parq": [
    52.3513635,
    4.9289951
  ],
  "aula": [
    52.4038292,
    4.909229
  ],
  "b-amsterdam": [
    52.3431327,
    4.829125500000001
  ],
  "back-to-black": [
    52.361076999999995,
    4.888494
  ],
  "back-to-black-2": [
    52.379399299999996,
    4.8714727
  ],
  "badeta-coffee-van-wou-albert-cuyp-market": [
    52.3569733,
    4.8994519
  ],
  "badeta-koffiebranders": [
    52.352381199999996,
    4.894745200000001
  ],
  "badeta-koffiebranders-watergraafsmeer": [
    52.3505682,
    4.9385593
  ],
  "bagels-beans": [
    52.360959199999996,
    4.8676433
  ],
  "bagels-beans-10": [
    52.358526100000006,
    4.9897339
  ],
  "bagels-beans-11": [
    52.375288,
    4.862373799999999
  ],
  "bagels-beans-12": [
    52.3558467,
    4.9290236
  ],
  "bagels-beans-13": [
    52.4045999,
    4.8899664
  ],
  "bagels-beans-14": [
    52.391429699999996,
    4.8778622
  ],
  "bagels-beans-2": [
    52.365913400000004,
    4.8858824
  ],
  "bagels-beans-3": [
    52.3734803,
    4.8880187
  ],
  "bagels-beans-4": [
    52.355258899999995,
    4.8899732
  ],
  "bagels-beans-5": [
    52.368708,
    4.9003843
  ],
  "bagels-beans-6": [
    52.3781696,
    4.8482157
  ],
  "bagels-beans-7": [
    52.3416852,
    4.868061
  ],
  "bagels-beans-8": [
    52.3845989,
    4.8946874
  ],
  "bagels-beans-9": [
    52.3353938,
    4.8842213
  ],
  "bagels-beans-de-clercqstraat-amsterdam": [
    52.3716757,
    4.8728764
  ],
  "bagels-beans-overhoeks": [
    52.3848686,
    4.9035082999999995
  ],
  "bagels-beans-roetersstraat-plantagebuurt": [
    52.364047,
    4.910628
  ],
  "bakers-roasters": [
    52.357288999999994,
    4.8898554
  ],
  "bakers-roasters-2": [
    52.3701953,
    4.9126142
  ],
  "bakery-cafe-lupin": [
    52.3671832,
    4.8724373
  ],
  "bakhuys-amsterdam": [
    52.3611217,
    4.9068606
  ],
  "baking-lab-amsterdam": [
    52.358467499999996,
    4.9265954
  ],
  "bakker-jongejans": [
    52.331014599999996,
    4.8788602999999995
  ],
  "bakkerij-mas": [
    52.3568109,
    4.937013500000001
  ],
  "bakkerswinkel-westerpark-amsterdam": [
    52.3858058,
    4.8746378
  ],
  "bapa-collective": [
    52.3624095,
    4.9358854999999995
  ],
  "bar-botanique": [
    52.363422,
    4.930292199999999
  ],
  "bar-bouwmeester": [
    52.3473341,
    4.904601700000001
  ],
  "bar-bukowski": [
    52.3579617,
    4.9176701
  ],
  "bar-exit": [
    52.3662834,
    4.8912876999999995
  ],
  "bar-kitchen-de-zuid": [
    52.3765412,
    4.9377379999999995
  ],
  "bar-restaurant-lely": [
    52.35722750000001,
    4.8352555
  ],
  "bar-staal": [
    52.3476146,
    4.850613
  ],
  "bariq-greek-food-wines": [
    52.3591063,
    4.861316899999999
  ],
  "barmhartig-koffie": [
    52.374092,
    4.938664999999999
  ],
  "barney-s-coffeeshop-amsterdam-thc-cannabis-dispensary": [
    52.3806892,
    4.8908553
  ],
  "basjoe": [
    52.3700312,
    4.8973492
  ],
  "bbrood": [
    52.3728294,
    4.8777459
  ],
  "bbrood-2": [
    52.3627354,
    4.8641606
  ],
  "bbrood-3": [
    52.401452199999994,
    4.8922142
  ],
  "bbrood-4": [
    52.37832590000001,
    4.8491156
  ],
  "bbrood-5": [
    52.34934,
    4.877863
  ],
  "bbrood-watergraafsmeer": [
    52.349889,
    4.93908
  ],
  "bean-there-co": [
    52.3736652,
    4.9678066
  ],
  "beef-chief-transit-bar": [
    52.38449860000001,
    4.9288488
  ],
  "beer-tasting-room-in-the-wildeman": [
    52.376117900000004,
    4.8951025
  ],
  "bendito-cafe": [
    52.374958,
    4.8625223
  ],
  "benji-s": [
    52.3658177,
    4.8605228
  ],
  "benji-s-2": [
    52.352363499999996,
    4.9127833999999995
  ],
  "benji-s-3": [
    52.3488902,
    4.8369328
  ],
  "bereket-baklava": [
    52.3792249,
    4.8339783
  ],
  "berry-amsterdam": [
    52.3683963,
    4.8702043
  ],
  "bertus-coffee-pastries": [
    52.363268999999995,
    4.9192148
  ],
  "best-bread-boba": [
    52.3557707,
    4.8804590999999995
  ],
  "beta-boulders-amsterdam": [
    52.344187999999995,
    4.8558218
  ],
  "beyou-amsterdam": [
    52.366406,
    4.8600115
  ],
  "bij-8-eraf": [
    52.3425102,
    4.7951646
  ],
  "billiards-cafe-hermes": [
    52.352700000000006,
    4.889200000000001
  ],
  "black-and-blue": [
    52.375747200000006,
    4.8854076
  ],
  "black-gold-amsterdam": [
    52.371787999999995,
    4.9030432
  ],
  "blck-coffee-and-the-masters": [
    52.337189599999995,
    4.869553499999999
  ],
  "blend-coffee-wine": [
    52.3565034,
    4.9302914
  ],
  "blue-lagoon": [
    52.360617999999995,
    4.866269
  ],
  "bluey-s-coffee-kitchen": [
    52.3733928,
    4.9640642
  ],
  "bluey-s-coffee-kitchen-2": [
    52.3404041,
    4.873473100000001
  ],
  "blushing": [
    52.3588108,
    4.8803583999999995
  ],
  "bo-s-amsterdam": [
    52.364872999999996,
    4.8597585
  ],
  "bocca-coffee": [
    52.3643905,
    4.8868164
  ],
  "boefzak": [
    52.368361,
    4.9537889999999996
  ],
  "boes-beis": [
    52.3729223,
    4.8383473
  ],
  "boka-s": [
    52.38809380000001,
    4.9094264999999995
  ],
  "boon-chance-koffie-bar": [
    52.379217000000004,
    4.8201385
  ],
  "borista-koffie-ontbijt-en-lunch": [
    52.355420699999996,
    4.937748399999999
  ],
  "bosco": [
    52.365212799999995,
    4.8739235999999995
  ],
  "boulevard-cafe": [
    52.3686133,
    4.934453899999999
  ],
  "bouncespace-coffee-coworking": [
    52.361863500000005,
    4.8729211
  ],
  "box-sociaal": [
    52.3662418,
    4.9118704
  ],
  "box-sociaal-jordaan": [
    52.374667099999996,
    4.8814858
  ],
  "brandmeesters-amsterdam": [
    52.3447074,
    4.8948719
  ],
  "brasserie-hoekenrode": [
    52.3131046,
    4.9482374
  ],
  "brasserie-lolita": [
    52.3555364,
    4.890289
  ],
  "brasserie-nenette": [
    52.3424246,
    4.8927799
  ],
  "brasserie-vrijburcht": [
    52.361045999999995,
    4.9755471
  ],
  "breadwinner-de-pijp": [
    52.3542785,
    4.8852269
  ],
  "breadwinner-jordaan": [
    52.371518099999996,
    4.8792632
  ],
  "broodje-popov": [
    52.3567883,
    4.8995524999999995
  ],
  "broodje-snackbar-tip-top": [
    52.32593,
    4.882791699999999
  ],
  "brouwerij-en-proeflokaal-breugem": [
    52.393616699999995,
    4.867312699999999
  ],
  "brunos": [
    52.381000199999995,
    4.8840619
  ],
  "bullewijck": [
    52.3069053,
    4.948297999999999
  ],
  "buno-coffee-amstel": [
    52.3460963,
    4.9193333
  ],
  "buno-coffee-hoofddorpplein": [
    52.3513152,
    4.850585199999999
  ],
  "buongiorno-espresso-bar": [
    52.3806765,
    4.8549457
  ],
  "buongiorno-espresso-bar-2": [
    52.3788006,
    4.847148499999999
  ],
  "buongiorno-espressobar": [
    52.3707068,
    4.863033
  ],
  "buro-de-pijp": [
    52.353861099999996,
    4.8901354
  ],
  "buurman-de-with": [
    52.3688262,
    4.8592942
  ],
  "buurtcafe-de-tros": [
    52.360455099999996,
    4.9254231
  ],
  "caf-koffiehuis-aquarius-amsterdam-zuidoost": [
    52.3160963,
    4.9817458
  ],
  "cafe-americain": [
    52.363831499999996,
    4.881536800000001
  ],
  "cafe-anno-1890": [
    52.322358799999996,
    4.8572017999999995
  ],
  "cafe-atelier": [
    52.364118500000004,
    4.8555734
  ],
  "cafe-aunt-rosie": [
    52.366435,
    4.896027999999999
  ],
  "cafe-barlotta": [
    52.3713457,
    4.9312035
  ],
  "cafe-baskets": [
    52.3565085,
    4.8927591999999995
  ],
  "cafe-bax": [
    52.365613,
    4.867942
  ],
  "cafe-bedier": [
    52.3524874,
    4.8565198
  ],
  "cafe-belcampo": [
    52.3668894,
    4.8688723
  ],
  "cafe-berkhout": [
    52.357934699999994,
    4.8906833999999995
  ],
  "cafe-bica": [
    52.3557512,
    4.9074905
  ],
  "cafe-biljart-janszen": [
    52.3719922,
    4.8713289
  ],
  "cafe-binnen-buiten": [
    52.3547976,
    4.8872165
  ],
  "cafe-binnenvisser": [
    52.371525399999996,
    4.8704009
  ],
  "cafe-bolle-jan": [
    52.3660127,
    4.8952097
  ],
  "cafe-bouwman": [
    52.362308299999995,
    4.8987944
  ],
  "cafe-brecht": [
    52.359805200000004,
    4.8900679
  ],
  "cafe-brel": [
    52.3841654,
    4.870256599999999
  ],
  "cafe-casa-sofia": [
    52.3475253,
    4.8256263
  ],
  "cafe-conrad": [
    52.357568,
    4.8575156999999995
  ],
  "cafe-cook": [
    52.3712896,
    4.8526245999999995
  ],
  "cafe-coos": [
    52.3689349,
    4.8698464
  ],
  "cafe-cress": [
    52.395785,
    4.904281699999999
  ],
  "cafe-dapper": [
    52.3641678,
    4.9263202999999995
  ],
  "cafe-de-amstel": [
    52.3486111,
    4.9030556
  ],
  "cafe-de-baron-amsterdam": [
    52.356936999999995,
    4.896787000000001
  ],
  "cafe-de-bult-b-v": [
    52.391596,
    4.913067
  ],
  "cafe-de-ceuvel": [
    52.3933105,
    4.9106865
  ],
  "cafe-de-doffer": [
    52.3689853,
    4.8836337
  ],
  "cafe-de-dokter": [
    52.3692539,
    4.8908111
  ],
  "cafe-de-jaren": [
    52.368068799999996,
    4.8954201
  ],
  "cafe-de-klepel": [
    52.377940599999995,
    4.8868202
  ],
  "cafe-de-krater": [
    52.3638269,
    4.9111492000000005
  ],
  "cafe-de-laurierboom": [
    52.372299999999996,
    4.8809499999999995
  ],
  "cafe-de-muurbloem": [
    52.374171,
    4.877737
  ],
  "cafe-de-nieuwe-stek": [
    52.361010099999994,
    4.9283516
  ],
  "cafe-de-orchidee": [
    52.3291129,
    4.895082599999999
  ],
  "cafe-de-pels": [
    52.368755,
    4.885263
  ],
  "cafe-de-plakhoek": [
    52.3505634,
    4.8898426
  ],
  "cafe-eik-en-linde": [
    52.3665047,
    4.9108772
  ],
  "cafe-fest": [
    52.359634299999996,
    4.9104601
  ],
  "cafe-het-molenpad-cafe-amsterdam": [
    52.367210899999996,
    4.8828664999999996
  ],
  "cafe-hill-street-blues": [
    52.375479,
    4.898224
  ],
  "cafe-insulinde": [
    52.364218699999995,
    4.9351619
  ],
  "cafe-jansen-bajeskwartier": [
    52.336963999999995,
    4.9261598
  ],
  "cafe-jansen-schinkel": [
    52.342071999999995,
    4.845875700000001
  ],
  "cafe-joselito": [
    52.378823499999996,
    4.8946862
  ],
  "cafe-karpershoek": [
    52.378185099999996,
    4.8967176
  ],
  "cafe-kiebert": [
    52.3483706,
    4.8605911
  ],
  "cafe-ko-kiss-bakery": [
    52.35973990000001,
    4.9083353999999995
  ],
  "cafe-koffiehuis-blokker": [
    52.390852599999995,
    4.9131437
  ],
  "cafe-koffiehuis-nieuwland": [
    52.3619047,
    4.9284129
  ],
  "cafe-kontakt": [
    52.3720181,
    4.8595897
  ],
  "cafe-koosje": [
    52.366642899999995,
    4.9116501999999995
  ],
  "cafe-krom": [
    52.362946300000004,
    4.8985451
  ],
  "cafe-langereis": [
    52.36612900000001,
    4.9001399
  ],
  "cafe-mads": [
    52.3885736,
    4.8861621
  ],
  "cafe-magari": [
    52.3689865,
    4.8883166
  ],
  "cafe-maha-amsterdam": [
    52.363139800000006,
    4.8923606
  ],
  "cafe-mankind": [
    52.3607729,
    4.8882255
  ],
  "cafe-marcella": [
    52.362249,
    4.8982857
  ],
  "cafe-marktzicht": [
    52.3752357,
    4.8709631
  ],
  "cafe-nassau": [
    52.3828713,
    4.8771830000000005
  ],
  "cafe-nieuw-amsterdam": [
    52.3801803,
    4.8919698
  ],
  "cafe-noir": [
    52.361821199999994,
    4.90825
  ],
  "cafe-nol": [
    52.37829,
    4.883390299999999
  ],
  "cafe-nosso": [
    52.3479837,
    4.904310199999999
  ],
  "cafe-old-sailor": [
    52.37371100000001,
    4.899558
  ],
  "cafe-olympia": [
    52.3610055,
    4.8649197
  ],
  "cafe-oost": [
    52.3534727,
    4.9198154
  ],
  "cafe-orloff-amsterdam": [
    52.370312999999996,
    4.9123695
  ],
  "cafe-osdorp": [
    52.354065500000004,
    4.8110707
  ],
  "cafe-peep": [
    52.3656739,
    4.9396838
  ],
  "cafe-pek": [
    52.3870228,
    4.9078270999999996
  ],
  "cafe-piazza": [
    52.3719116,
    4.9000787
  ],
  "cafe-plan-west": [
    52.3713324,
    4.8592013
  ],
  "cafe-restaurant-camping-zeeburg": [
    52.365401399999996,
    4.9594916
  ],
  "cafe-restaurant-czaar": [
    52.37184740000001,
    4.9318251
  ],
  "cafe-restaurant-dauphine": [
    52.3483759,
    4.9173295
  ],
  "cafe-restaurant-de-baanderij": [
    52.4014995,
    4.8910814
  ],
  "cafe-restaurant-de-ysbreeker": [
    52.357461799999996,
    4.9067549999999995
  ],
  "cafe-restaurant-verlan": [
    52.3715741,
    4.8832417999999995
  ],
  "cafe-sarphaat": [
    52.354373499999994,
    4.899266
  ],
  "cafe-slijterij-oosterling": [
    52.3610581,
    4.8992838
  ],
  "cafe-soleil-amsterdam": [
    52.3934867,
    4.9118251
  ],
  "cafe-sonneveld": [
    52.3763328,
    4.882285899999999
  ],
  "cafe-susy": [
    52.354881999999996,
    4.9216500000000005
  ],
  "cafe-t-gasthuys": [
    52.3694444,
    4.8936111
  ],
  "cafe-t-podium-shane": [
    52.3525719,
    4.8908398
  ],
  "cafe-t-ruysje": [
    52.382533699999996,
    4.804799699999999
  ],
  "cafe-t-vossie": [
    52.359536,
    4.8518858
  ],
  "cafe-the-minds": [
    52.370820599999995,
    4.8893398999999995
  ],
  "cafe-the-star": [
    52.3779678,
    4.896065699999999
  ],
  "cafe-thijssen": [
    52.380810399999994,
    4.8873031
  ],
  "cafe-thuys": [
    52.369906099999994,
    4.8653762
  ],
  "cafe-treffers": [
    52.371021299999995,
    4.863151200000001
  ],
  "cafe-van-leeuwen": [
    52.364070999999996,
    4.898372
  ],
  "cafe-van-wou": [
    52.3567168,
    4.90004
  ],
  "cafe-van-zuylen": [
    52.3745828,
    4.8898545
  ],
  "cafe-vienna": [
    52.3590975,
    4.8281781
  ],
  "cafe-viotta": [
    52.3561091,
    4.8793850999999995
  ],
  "cafe-vrijdag-amsterdam": [
    52.3466667,
    4.911111099999999
  ],
  "cafe-waterlooplein-77": [
    52.368364199999995,
    4.9062994
  ],
  "cafe-westerdok": [
    52.389318499999995,
    4.891229099999999
  ],
  "cafe-wildschut": [
    52.3534218,
    4.8822933
  ],
  "cafe-zomerlust": [
    52.381276799999995,
    4.8239225999999995
  ],
  "cafecito": [
    52.3542065,
    4.8816198
  ],
  "cafecito-2": [
    52.347421499999996,
    4.9044622
  ],
  "cafecito-3": [
    52.3554137,
    4.9278482
  ],
  "cafecito-4": [
    52.3492805,
    4.8778543999999995
  ],
  "cafecito-5": [
    52.3743001,
    4.8738078
  ],
  "cafecito-nassaukade-coffeebar": [
    52.3683996,
    4.8759174
  ],
  "cafecito-overtoom-specialty-coffee-matcha": [
    52.358904499999994,
    4.8606422
  ],
  "caffe-belmondo-wtc": [
    52.340302699999995,
    4.8728074
  ],
  "caffe-il-momento": [
    52.374684599999995,
    4.8890461
  ],
  "caffenation-amsterdam": [
    52.354718,
    4.8493189999999995
  ],
  "camping-zeeburg-amsterdam": [
    52.365333899999996,
    4.959441099999999
  ],
  "cana-ijburg": [
    52.3531457,
    5.0059188
  ],
  "cantuccio": [
    52.362533000000006,
    4.86391
  ],
  "canvas-ateliers-art-cafe-workshops": [
    52.350938,
    4.9032333
  ],
  "capital-kitchen": [
    52.3619902,
    4.9069378
  ],
  "caprichosa-restaurant": [
    52.4009679,
    4.9443234
  ],
  "carmen-amsterdam": [
    52.364008000000005,
    4.8896118
  ],
  "carroll-s": [
    52.4014971,
    4.8917015
  ],
  "carstens-cafe": [
    52.3775329,
    4.8973922
  ],
  "chateau-karlito": [
    52.388203,
    4.9089089999999995
  ],
  "cheeky": [
    52.3845106,
    4.8732028
  ],
  "chef-coffee-drinks-events": [
    52.357698799999994,
    4.8523333
  ],
  "chimney-cake-bakery-cafe": [
    52.356914599999996,
    4.8791179
  ],
  "chris-scholten-cafe": [
    52.354293299999995,
    4.9014622
  ],
  "clapham-specialty-coffee": [
    52.3562255,
    4.8710219
  ],
  "cloud": [
    52.3709324,
    4.8824399
  ],
  "cobra-cafe": [
    52.358910099999996,
    4.8843635999999995
  ],
  "coffee-and-cakes-amsterdam-tea-matcha-chai-wifi-muffin": [
    52.369185300000005,
    4.8882686
  ],
  "coffee-and-kids": [
    52.3535911,
    4.9990305
  ],
  "coffee-atelier": [
    52.3546325,
    4.8412185
  ],
  "coffee-bites": [
    52.365945499999995,
    4.9125043999999995
  ],
  "coffee-blends": [
    52.358689899999995,
    4.8014841
  ],
  "coffee-bru": [
    52.3570888,
    4.9177032999999994
  ],
  "coffee-bru-2": [
    52.3538168,
    4.902360799999999
  ],
  "coffee-cakes": [
    52.3738628,
    4.896120799999999
  ],
  "coffee-cakes-2": [
    52.3706508,
    4.8910036
  ],
  "coffee-coconuts-specialty-coffee-pastry-matcha-food-to-go": [
    52.337125,
    4.87311
  ],
  "coffee-company": [
    52.356311299999994,
    4.8904122
  ],
  "coffee-company-2": [
    52.364119699999996,
    4.9392271
  ],
  "coffee-company-3": [
    52.382508400000006,
    4.8876262
  ],
  "coffee-company-4": [
    52.3543552,
    4.9293689999999994
  ],
  "coffee-district": [
    52.3463448,
    4.868172599999999
  ],
  "coffee-district-buitenveldert": [
    52.3271221,
    4.868344899999999
  ],
  "coffee-district-willemsparkweg": [
    52.3580214,
    4.8776462
  ],
  "coffee-ice-cream-by-capital-kitchen": [
    52.3619902,
    4.9069378
  ],
  "coffee-juices": [
    52.358862099999996,
    4.8551817999999995
  ],
  "coffee-juices-2": [
    52.3750085,
    4.8725290999999995
  ],
  "coffee-juices-3": [
    52.3746539,
    4.8595043
  ],
  "coffee-lounge-west": [
    52.3632554,
    4.8746126
  ],
  "coffee-mama": [
    52.353221000000005,
    5.0034866
  ],
  "coffee-room": [
    52.367047199999995,
    4.8711193999999995
  ],
  "coffee-shop": [
    52.364776199999994,
    4.8980473
  ],
  "coffee-shop-2": [
    52.3912015,
    4.8299031
  ],
  "coffee-tales": [
    52.365950299999994,
    4.8949524
  ],
  "coffeebite": [
    52.3859656,
    4.8812047
  ],
  "coffeecompany": [
    52.364985,
    4.862749
  ],
  "coffeecompany-2": [
    52.371636099999996,
    4.8967306
  ],
  "coffeecompany-3": [
    52.365727799999995,
    4.910724999999999
  ],
  "coffeecompany-4": [
    52.3758783,
    4.9076772
  ],
  "coffeecompany-5": [
    52.3580213,
    4.9103324
  ],
  "coffeecompany-6": [
    52.3465184,
    4.8912844
  ],
  "coffeecompany-7": [
    52.35489,
    4.9009279999999995
  ],
  "coffeecompany-8": [
    52.347302,
    4.8766543
  ],
  "coffeecompany-bos-en-lommer": [
    52.3782894,
    4.8463278999999995
  ],
  "coffeecompany-north-station": [
    52.401548700000006,
    4.9331027
  ],
  "coffeecompany-van-wou": [
    52.352607,
    4.903079
  ],
  "coffeeconcepts": [
    52.3577782,
    4.874293199999999
  ],
  "coffeehouse-gelderlandplein": [
    52.331065699999996,
    4.8773273
  ],
  "coffeeshop-amsterdam": [
    52.3800848,
    4.8929082
  ],
  "coffeeshop-bronx": [
    52.3791088,
    4.8793562999999995
  ],
  "coffeeshop-carmona": [
    52.3556709,
    4.9010704
  ],
  "coffeeshop-central": [
    52.3767193,
    4.9019128
  ],
  "coffeeshop-de-supermarkt": [
    52.3757756,
    4.873823
  ],
  "coffeeshop-drewissharing-by-mediterrane": [
    52.375609999999995,
    4.8915806
  ],
  "coffeeshop-el-marssa": [
    52.3690067,
    4.8593055
  ],
  "coffeeshop-get-down": [
    52.36401,
    4.8838
  ],
  "coffeeshop-ibiza": [
    52.357444799999996,
    4.9020715
  ],
  "coffeeshop-la-tertulia": [
    52.3694808,
    4.8822851
  ],
  "coffeeshop-relax": [
    52.3484609,
    4.9056009
  ],
  "coffeeshop-relax-amsterdam-centrum": [
    52.3821959,
    4.8871458
  ],
  "coffeeshop-roxy": [
    52.3563955,
    4.8956237
  ],
  "coffeeshop-s-w-e-d": [
    52.3727133,
    4.8761101
  ],
  "coffeeshop-siberie": [
    52.3788926,
    4.892991
  ],
  "coffeeshop-terps-army-2": [
    52.361670000000004,
    4.8861140999999995
  ],
  "coffeeshop-the-jolly-joker": [
    52.373047,
    4.9001559
  ],
  "coffeeshop-the-otherside": [
    52.366780000000006,
    4.8892359999999995
  ],
  "comedy-cafe-amsterdam": [
    52.3844407,
    4.8948848
  ],
  "concerto-koffie": [
    52.363448899999995,
    4.898373800000001
  ],
  "conscious-cafe": [
    52.3866903,
    4.8753421
  ],
  "corner-bakery": [
    52.3547191,
    4.8840308
  ],
  "cotti-coffee-weesperplein-metro-station": [
    52.3615521,
    4.9081266
  ],
  "craft-coffee-pastry-amsterdam": [
    52.356151999999994,
    4.8934824
  ],
  "crea": [
    52.363298,
    4.9129983
  ],
  "crew-de-la-crema": [
    52.3906182,
    4.8740746
  ],
  "croissanterie-balans": [
    52.379539199999996,
    4.871080699999999
  ],
  "croissanterie-eifeltoren": [
    52.3517284,
    4.847796499999999
  ],
  "croque-madame-gluten-free-food": [
    52.3739037,
    4.8969192
  ],
  "ct-coffee-and-coconuts": [
    52.352607899999995,
    4.891426699999999
  ],
  "cultureel-eetcafe-skek": [
    52.376065,
    4.900176
  ],
  "cups-chapters-cafe": [
    52.3848407,
    4.9169338
  ],
  "daffee": [
    52.344676199999995,
    4.8362376
  ],
  "dak-coffee-roasters": [
    52.3684127,
    4.867310499999999
  ],
  "dam-tasty": [
    52.35076850000001,
    4.8543194
  ],
  "darras-coffee-roasters-amsterdam": [
    52.40020390000001,
    4.8415802
  ],
  "de-bekeerde-suster-restaurant": [
    52.3720633,
    4.8992274
  ],
  "de-blauwe-engel": [
    52.34059130000001,
    4.8734951
  ],
  "de-buurman-farouk": [
    52.363846599999995,
    4.8413902
  ],
  "de-deli-haarlemmerbuurt": [
    52.3849823,
    4.883892299999999
  ],
  "de-deli-plantagebuurt": [
    52.3669772,
    4.9120382
  ],
  "de-eeuwige-jeugd": [
    52.3614031,
    4.924726499999999
  ],
  "de-graal-health-cafe": [
    52.354717199999996,
    4.8876118
  ],
  "de-groene-vlinder": [
    52.3553711,
    4.8930242
  ],
  "de-huismeesters": [
    52.3872924,
    4.8417933
  ],
  "de-huismeesters-2": [
    52.3511333,
    4.836011
  ],
  "de-huismeesters-3": [
    52.3311495,
    4.931537
  ],
  "de-jonge-admiraal": [
    52.363943,
    4.93825
  ],
  "de-knip-bar": [
    52.3508771,
    4.8510158
  ],
  "de-koffie-broeder": [
    52.3706743,
    4.9301778
  ],
  "de-koffie-salon-centrum": [
    52.361290999999994,
    4.8991549999999995
  ],
  "de-koffiesalon-spui": [
    52.3695824,
    4.8890002
  ],
  "de-koffieschenkerij": [
    52.3741148,
    4.898346699999999
  ],
  "de-lachende-gulden": [
    52.364433,
    4.9261896
  ],
  "de-oranjerie": [
    52.3819861,
    4.88685
  ],
  "de-overkant": [
    52.3673263,
    4.906465799999999
  ],
  "de-parkwachter": [
    52.3877301,
    4.8753456
  ],
  "de-proefzaak-amsterdam": [
    52.3035771,
    4.9511329
  ],
  "de-sering-centraal": [
    52.3765295,
    4.913177999999999
  ],
  "de-spiegel": [
    52.3622336,
    4.8863385
  ],
  "de-wasserette": [
    52.3558251,
    4.8931406
  ],
  "dickys-grand-cafe": [
    52.336875299999996,
    4.8730272999999995
  ],
  "dignita-hoftuin": [
    52.3656404,
    4.9044574
  ],
  "doppio-espresso": [
    52.365804399999995,
    4.8674656999999995
  ],
  "doppio-espresso-amsterdam-vu": [
    52.3339764,
    4.8659922
  ],
  "doppio-espresso-amsterdam-zuidas": [
    52.336807699999994,
    4.8727225999999995
  ],
  "douwe-egberts-cafe-slotervaart": [
    52.3476739,
    4.8252852
  ],
  "douwe-egberts-cafe-zandkasteel": [
    52.313731999999995,
    4.9522051
  ],
  "drupa-coffee-roasters": [
    52.3781142,
    4.8833142
  ],
  "duende-dos": [
    52.3807971,
    4.8809001
  ],
  "dunkin": [
    52.3667351,
    4.8945833
  ],
  "dunkin-2": [
    52.3783801,
    4.900459000000001
  ],
  "dwaze-zaken": [
    52.3765423,
    4.8993207
  ],
  "ecluse": [
    52.363834000000004,
    4.981364
  ],
  "eetcafe-100-zuid-oost": [
    52.3148165,
    4.9535450999999995
  ],
  "eetcafe-dorus-amsterdam": [
    52.3712902,
    4.8726537
  ],
  "eetcafe-maxwell": [
    52.356801999999995,
    4.9186499999999995
  ],
  "eetcafe-rosereijn": [
    52.382346899999995,
    4.8879166000000005
  ],
  "elevate-coffee-lab": [
    52.351573200000004,
    4.8945191999999995
  ],
  "elsa-s-cafe": [
    52.353186099999995,
    4.9319667
  ],
  "espresso-yourself": [
    52.3599458,
    4.9095835
  ],
  "espressofabriek": [
    52.3861402,
    4.8719319
  ],
  "espressofabriek-ijburg": [
    52.351933499999994,
    5.0019646
  ],
  "esthetique-cafe": [
    52.350439099999996,
    4.8602669999999994
  ],
  "fa-cafe-bistro-hansel-and-gretel": [
    52.3617899,
    4.8873837
  ],
  "factor-ij": [
    52.3515927,
    5.0052636
  ],
  "fanke-coffee-amsterdam": [
    52.3731553,
    4.8803854
  ],
  "farine-bakery-boulangerie-cafe": [
    52.3822653,
    4.8552382
  ],
  "ferilli-s-caffe-ristorante": [
    52.3499857,
    4.8778675
  ],
  "ferment-wine-coffee": [
    52.381628199999994,
    4.8711869
  ],
  "fermento-bakery": [
    52.3645486,
    4.8607698
  ],
  "festina-lente": [
    52.368652999999995,
    4.881389599999999
  ],
  "fika-amsterdam-mercatorplein": [
    52.369699399999995,
    4.8516574
  ],
  "filmtheater-kriterion": [
    52.362528,
    4.910711699999999
  ],
  "first-coffee": [
    52.3859437,
    4.8814264
  ],
  "five-stars-cafe": [
    52.356036,
    4.9088766
  ],
  "five-ways-coffee-roasters": [
    52.3598712,
    4.9123059
  ],
  "five-ways-west": [
    52.366029499999996,
    4.8673108
  ],
  "flo-s-appetizing-amsterdam": [
    52.362351,
    4.8644367
  ],
  "flow-all-day-brunch": [
    52.35750900000001,
    4.889818
  ],
  "fonda-cafe-and-coffee-bar": [
    52.3577419,
    4.879932
  ],
  "footnote-coffee": [
    52.353151499999996,
    4.9023335
  ],
  "fret-restobar": [
    52.389771499999995,
    4.8373677
  ],
  "friedhats-fuku-cafe": [
    52.3812737,
    4.855158100000001
  ],
  "galerie-coffeeshop-yoyo": [
    52.3563656,
    4.9031321
  ],
  "generator-amsterdam": [
    52.3608673,
    4.919017600000001
  ],
  "gentle-place-coffee": [
    52.394723000000006,
    4.8998311
  ],
  "george-deli": [
    52.39617510000001,
    4.8798956
  ],
  "glazemade": [
    52.3538603,
    4.9023166
  ],
  "good-beans-coffee": [
    52.382381,
    4.887274199999999
  ],
  "goodnews-coffee-constantijn-67": [
    52.3631981,
    4.875329
  ],
  "goos-amsterdam": [
    52.344877999999994,
    4.894836
  ],
  "gorgo-lunchroom": [
    52.360279999999996,
    4.86313
  ],
  "graca-coffee-sweets": [
    52.3580189,
    4.8058999
  ],
  "grammes": [
    52.347245799999996,
    4.894953699999999
  ],
  "grand-cafe-3-20": [
    52.312636,
    4.9389177
  ],
  "grand-cafe-het-paviljoen": [
    52.3811981,
    4.8701057
  ],
  "grand-cafe-rox": [
    52.312336099999996,
    4.9387139
  ],
  "gratitude-espresso": [
    52.3441743,
    4.895774200000001
  ],
  "green-place": [
    52.3721177,
    4.8992756
  ],
  "green-place-coffeeshop-haarlemmerstraat": [
    52.3794428,
    4.8940335
  ],
  "greenwoods-singel": [
    52.3758,
    4.891298
  ],
  "grolsch-pub": [
    52.3129893,
    4.9424874999999995
  ],
  "guji-coffee": [
    52.388345,
    4.8855949999999995
  ],
  "hagen-espresso-bar-hagen-kleine-gartmanplantsoen": [
    52.3625541,
    4.8835014999999995
  ],
  "hagen-espresso-bar-hagen-middenweg": [
    52.353792399999996,
    4.9309974
  ],
  "hair-plus": [
    52.3738684,
    4.9642589
  ],
  "haku-specialty-coffee": [
    52.373287999999995,
    4.880800499999999
  ],
  "hannah-s-restaurant": [
    52.372439899999996,
    4.8590253
  ],
  "hannekes-boom": [
    52.376247,
    4.911607
  ],
  "happy-people": [
    52.365172199999996,
    4.9258133
  ],
  "harmani-coffee-brunch": [
    52.354886799999996,
    4.888565
  ],
  "hartbiet-koksopleiding": [
    52.3621312,
    4.8566401
  ],
  "hartje-bos": [
    52.379118,
    4.856485
  ],
  "harvey-amsterdam": [
    52.354473299999995,
    4.941558199999999
  ],
  "hejo-coffee": [
    52.3617365,
    4.864937299999999
  ],
  "hello-couscous-traditioneel-marokkaans-eten": [
    52.3868296,
    4.9263769
  ],
  "hemelsbreed-cafe": [
    52.3156542,
    4.9772473999999995
  ],
  "hendrix": [
    52.3707358,
    4.8686881
  ],
  "het-ketelhuis-movie-theater-and-bar": [
    52.386375,
    4.8735
  ],
  "het-plantsoen": [
    52.3780291,
    4.8783669
  ],
  "hookah-lounge-amsterdam": [
    52.3647632,
    4.8620651
  ],
  "hortus-cafe-the-orangery": [
    52.3669986,
    4.9074042
  ],
  "hotel-cafe-de-zwaan": [
    52.3935928,
    4.994287
  ],
  "hotel-cafe-restaurant-abina": [
    52.3114504,
    4.8466305
  ],
  "hummingbird-coffee-amsterdam": [
    52.371586799999996,
    4.8895102999999995
  ],
  "hunter-s-coffeeshop-amsterdam-downtown": [
    52.3654954,
    4.8975366
  ],
  "hunter-s-coffeeshop-amsterdam-north-waterlandplein": [
    52.3923079,
    4.9561719
  ],
  "hunter-s-coffeeshop-amsterdam-west": [
    52.3699953,
    4.849033599999999
  ],
  "ijs-van-oost": [
    52.3638602,
    4.9347069
  ],
  "ijskoud-de-beste": [
    52.349504599999996,
    4.8277966
  ],
  "ijsland-smaakmakers": [
    52.345644899999996,
    4.895229
  ],
  "ijssalon-da-vinci-amsterdam": [
    52.3437657,
    4.8574728
  ],
  "ijssalon-tofani": [
    52.371841499999995,
    4.8990937
  ],
  "ikaria-food": [
    52.368778899999995,
    4.8708165
  ],
  "ikinari-coffee": [
    52.3692767,
    4.8729469
  ],
  "illy-caffe": [
    52.377486,
    4.897479
  ],
  "in-de-keuken": [
    52.4006665,
    4.875498599999999
  ],
  "italiaanse-cateraar-eatalia-gastronomia": [
    52.343011999999995,
    4.9068629999999995
  ],
  "ivy-and-bros": [
    52.373497,
    4.8975
  ],
  "jack-dish": [
    52.3444526,
    4.8584137
  ],
  "joe-the-juice": [
    52.363125399999994,
    4.8758172
  ],
  "joe-the-juice-10": [
    52.3443125,
    4.8576875
  ],
  "joe-the-juice-2": [
    52.368831699999994,
    4.8836029
  ],
  "joe-the-juice-3": [
    52.3540881,
    4.8717285
  ],
  "joe-the-juice-4": [
    52.358472,
    4.878023
  ],
  "joe-the-juice-5": [
    52.350040199999995,
    4.8785946
  ],
  "joe-the-juice-6": [
    52.3529701,
    4.891257599999999
  ],
  "joe-the-juice-7": [
    52.380187299999996,
    4.887535199999999
  ],
  "joe-the-juice-8": [
    52.3369711,
    4.8708876
  ],
  "joe-the-juice-9": [
    52.351349,
    4.903604
  ],
  "juicebrothers": [
    52.361256700000006,
    4.8646834
  ],
  "juicebrothers-de-pijp-van-woustraat": [
    52.352807399999996,
    4.9031147
  ],
  "juicebrothers-oud-zuid-heemstedestraat": [
    52.3517689,
    4.8488396
  ],
  "julia-s": [
    52.389184799999995,
    4.8376771
  ],
  "julia-s-2": [
    52.3465301,
    4.9179707
  ],
  "julia-s-amsterdam-centraal-ij-hal": [
    52.3799621,
    4.9003920999999995
  ],
  "julia-s-amsterdam-zuid": [
    52.3381614,
    4.8734464
  ],
  "k-s-store-gifts-english-books-inc-kids-coffee-more": [
    52.356913999999996,
    4.8901717
  ],
  "kaasbar-amsterdam": [
    52.357285999999995,
    4.8905666
  ],
  "kabelle-a-brand-new-social-studio-with-speciality-coffee-mat": [
    52.389651799999996,
    4.8486012999999994
  ],
  "kafe-kontrast": [
    52.352782399999995,
    4.8899634999999995
  ],
  "kafenion": [
    52.374677,
    4.8813721999999995
  ],
  "kaffe-amsterdam": [
    52.379020100000005,
    4.838235
  ],
  "kaffee": [
    52.362005499999995,
    4.9282680999999995
  ],
  "kaffee-kiip": [
    52.3697848,
    4.8515612
  ],
  "kaldi-amsterdam-utrechtsestraat": [
    52.3616975,
    4.8993359
  ],
  "kaldi-cafe-coffee-tea-van-woustraat": [
    52.357311900000006,
    4.8996717
  ],
  "kanarie": [
    52.3673149,
    4.8681182
  ],
  "karavaan": [
    52.3691357,
    4.8705438999999995
  ],
  "karel-s-coffee-kiosk": [
    52.3898484,
    4.8910751999999995
  ],
  "kattencafe-kopjes": [
    52.3703978,
    4.8553109
  ],
  "keyf-cafe-restaurant": [
    52.3515617,
    4.7965515
  ],
  "khaybar-coffee-roastery-shakshuka-speciality-coffee": [
    52.3864994,
    4.9271334
  ],
  "kikiboba": [
    52.356898799999996,
    4.8998985
  ],
  "king-s-cross": [
    52.3745288,
    4.8970813
  ],
  "kiosk": [
    52.3887551,
    4.8380265
  ],
  "kiosk-rembrandt-van-gogh": [
    52.359235399999996,
    4.8831811
  ],
  "klein-kalfje": [
    52.3224194,
    4.8950610999999995
  ],
  "ko-hi-coffee-club-joki": [
    52.369028,
    4.9533188
  ],
  "koffie-academie": [
    52.362382999999994,
    4.8746811
  ],
  "koffie-en-kringloop": [
    52.349787899999995,
    4.9041793
  ],
  "koffie-kater": [
    52.3624556,
    4.8834748
  ],
  "koffie-katoen-coffeebar-conceptstore": [
    52.350979599999995,
    4.8989119
  ],
  "koffie-zo": [
    52.3839601,
    4.8927051
  ],
  "koffiekar-amsterdam": [
    52.369203999999996,
    4.9445405
  ],
  "koffiespot": [
    52.3694002,
    4.8805982
  ],
  "kooi-coffeeshop": [
    52.366239300000004,
    4.8994313
  ],
  "kringloopwinkel-muna": [
    52.3553341,
    4.84145
  ],
  "kriterion-student-gas-station-and-carwash": [
    52.3689699,
    4.970562
  ],
  "kwekkeboom-banketbakkerij-noord": [
    52.3979558,
    4.9374154
  ],
  "kwekkeboom-banketbakkerij-oostpoort": [
    52.356956499999995,
    4.928459699999999
  ],
  "kwekkeboom-banketbakkerij-zuid": [
    52.3523867,
    4.8914357
  ],
  "kyo-klub": [
    52.3648472,
    4.8624205
  ],
  "la-bottega-by-chiara-s-food": [
    52.351005699999995,
    4.9037292
  ],
  "la-chesa": [
    52.367843,
    4.874744
  ],
  "la-dilettante-amsterdam-natural-wine-bar": [
    52.355880799999994,
    4.8885016
  ],
  "la-fucina": [
    52.3638986,
    4.9360754
  ],
  "la-la-ijs": [
    52.3670651,
    4.8711534
  ],
  "la-place": [
    52.367528899999996,
    4.8929236
  ],
  "la-place-express": [
    52.3691842,
    4.9027609
  ],
  "la-trattoria-ferilli-s-uptown": [
    52.336864500000004,
    4.8777662
  ],
  "lagom-amsterdam": [
    52.3705716,
    4.900796
  ],
  "lawa-ice-cream-cafe": [
    52.380469299999994,
    4.8206622
  ],
  "le-french-cafe-admiraal-de-ruijterweg": [
    52.3701322,
    4.8644805
  ],
  "le-french-cafe-javastraat": [
    52.3635145,
    4.9334488
  ],
  "le-pain-quotidien": [
    52.3546177,
    4.8720253
  ],
  "le-pain-quotidien-2": [
    52.331392099999995,
    4.8790056
  ],
  "le-pain-quotidien-3": [
    52.348373099999996,
    4.876782899999999
  ],
  "le-perron": [
    52.4014313,
    4.9332872
  ],
  "lebkov-sons-bijlmer-arena": [
    52.312807299999996,
    4.9491458999999995
  ],
  "lebkov-sons-roeterseiland": [
    52.362809399999996,
    4.911066
  ],
  "lebkov-sons-zuidas": [
    52.3374168,
    4.8701799
  ],
  "len-en-bonjour-caphe": [
    52.3977612,
    4.8732372999999995
  ],
  "levant-restaurant": [
    52.3610249,
    4.8873337
  ],
  "li-s-coffee-house": [
    52.3716192,
    4.8459498
  ],
  "liev-coffee-pastry": [
    52.352177,
    4.889130199999999
  ],
  "life-kicking": [
    52.352232,
    5.003881
  ],
  "lilo-s-cafe-en-game": [
    52.3869131,
    4.9055884999999995
  ],
  "live-amsterdam-pianobar": [
    52.365391699999996,
    4.8955139
  ],
  "locals-coffee-locals-jacob": [
    52.357547399999994,
    4.8891126
  ],
  "loop-51-vinyl-brunch-bar": [
    52.351320199999996,
    4.8895518
  ],
  "lost-in-amsterdam-lounge-cafe-cocktail-bar": [
    52.3785058,
    4.8952427
  ],
  "lot-sixty-one-coffee-roasters": [
    52.3668272,
    4.870314
  ],
  "lot61-amsterdam-centraal-station": [
    52.376894,
    4.9043325
  ],
  "lot61-coffee-roasters": [
    52.3515355,
    4.8602111
  ],
  "louf-oud-west": [
    52.3714613,
    4.870341499999999
  ],
  "louie-louie": [
    52.3630521,
    4.9238802999999995
  ],
  "louis": [
    52.3769883,
    4.8924797
  ],
  "lourens": [
    52.374744799999995,
    4.8882829999999995
  ],
  "lova-all-day-brunch-breakfast": [
    52.384194699999995,
    4.8846434
  ],
  "lovers-cafe": [
    52.3787458,
    4.8969043999999995
  ],
  "luma-coffee-lunch": [
    52.3649458,
    4.8575767999999995
  ],
  "lunchcafe-waterloo": [
    52.36842600000001,
    4.902717000000001
  ],
  "lunchroom-fika-amsterdam": [
    52.3671594,
    4.866560499999999
  ],
  "lunchroom-grannies-amsterdam": [
    52.350905399999995,
    4.849682
  ],
  "lunchroom-oase": [
    52.3609466,
    4.9327498
  ],
  "luuk-s-coffee-noordermarkt": [
    52.378763899999996,
    4.8862575
  ],
  "luuk-s-coffee-vijzelgracht": [
    52.360563500000005,
    4.8914177
  ],
  "maalder-coffee": [
    52.3111002,
    4.8471385
  ],
  "mabell": [
    52.3817327,
    4.8497256
  ],
  "machu": [
    52.362929699999995,
    4.8381649
  ],
  "madam-pancake-breakfast-brunch-lunch": [
    52.3749081,
    4.8987054
  ],
  "malabar-amsterdam": [
    52.379407799999996,
    4.9223913999999995
  ],
  "mangi-mangi": [
    52.3565191,
    4.837991
  ],
  "maracuya": [
    52.363878199999995,
    4.8634461
  ],
  "margo-s-amsterdam": [
    52.3682122,
    4.8670066
  ],
  "margo-s-amsterdam-2": [
    52.3777616,
    4.8835489999999995
  ],
  "markerhuisje": [
    52.3714868,
    4.9223083
  ],
  "market-27": [
    52.402057,
    4.9322978
  ],
  "mas-atelier": [
    52.355805,
    4.9257484
  ],
  "massimo-gelato-de-pijp": [
    52.3526271,
    4.8946160999999995
  ],
  "meatless-district": [
    52.370025999999996,
    4.87071
  ],
  "melly-s-cookie-bar": [
    52.3740056,
    4.891257599999999
  ],
  "milky-amsterdam": [
    52.375712199999995,
    4.8985934
  ],
  "millie-vanillie": [
    52.3688604,
    4.9486134999999996
  ],
  "mina-gallery-cafe": [
    52.3615316,
    4.8861077
  ],
  "miuz-gelato-de-pijp": [
    52.3577931,
    4.8906557
  ],
  "mlt-bakery-coffee": [
    52.3598745,
    4.8618342
  ],
  "mokafe": [
    52.344143300000006,
    4.9085551
  ],
  "monks-coffee-roasters": [
    52.3712151,
    4.8702463
  ],
  "moos": [
    52.389168299999994,
    4.879356
  ],
  "morjoy-to-go": [
    52.3589334,
    4.9489674
  ],
  "morlang-cafe-restaurant-amsterdam": [
    52.366414,
    4.886483999999999
  ],
  "morning-owl-coffee": [
    52.3746793,
    4.900868399999999
  ],
  "motion-coffee": [
    52.3633939,
    4.930052
  ],
  "mundi": [
    52.36444100000001,
    4.853974099999999
  ],
  "naked-espresso": [
    52.3736185,
    4.8923282
  ],
  "nana-coffee-house": [
    52.3511034,
    4.8492497000000006
  ],
  "nap-amsterdam": [
    52.352885,
    5.003269599999999
  ],
  "nargile-hut": [
    52.3460938,
    4.8390102
  ],
  "ndsm-cafe-ndsm-theater": [
    52.400594899999994,
    4.8969948
  ],
  "nescio-cafe-terrace": [
    52.360783399999995,
    4.9188025
  ],
  "new-dutch-amsterdam": [
    52.377925399999995,
    4.8856158
  ],
  "niemandsland": [
    52.388627299999996,
    4.8922333
  ],
  "nini-s-coffeebar-amsterdam": [
    52.357660700000004,
    4.9179296
  ],
  "nio-house-amsterdam": [
    52.3662668,
    4.886707299999999
  ],
  "nio-house-cafe-amsterdam": [
    52.366243399999995,
    4.8864866
  ],
  "no-man-s-art-gallery-de-bar": [
    52.3824293,
    4.8552896
  ],
  "noah-lieven": [
    52.347305999999996,
    4.8378749999999995
  ],
  "nobo-bubble-tea-noodles-cafe": [
    52.3640925,
    4.9058132
  ],
  "noi-coffee-eatery": [
    52.3701752,
    4.8518884
  ],
  "nomu": [
    52.3830137,
    4.8868273
  ],
  "noon-coffee-culture": [
    52.352624299999995,
    4.9473817
  ],
  "noord-tuin-cafe": [
    52.414349599999994,
    4.8857876
  ],
  "noorderlicht-cafe": [
    52.399572,
    4.896833
  ],
  "noorderling-ijs-shakes-espresso": [
    52.401850599999996,
    4.8908526
  ],
  "nous-coffee-store": [
    52.3843793,
    4.8831798
  ],
  "nous-coffee-store-docklandsweg": [
    52.388137799999996,
    4.9049721
  ],
  "nrd": [
    52.3897669,
    4.9048148
  ],
  "nu-koffie-delicatessen": [
    52.37659310000001,
    4.8822931
  ],
  "oba-cafe-oosterdok": [
    52.376104,
    4.9082883
  ],
  "ode-aan-de-amstel": [
    52.3434384,
    4.914918000000001
  ],
  "oma-ietje": [
    52.306494699999995,
    4.9539175
  ],
  "orchid-house": [
    52.361785399999995,
    4.9228622
  ],
  "oslo": [
    52.3778611,
    4.887063599999999
  ],
  "out-of-office-coffee": [
    52.3850911,
    4.8672716
  ],
  "pannenkoekenhuis-candela": [
    52.370171,
    4.8707519999999995
  ],
  "papa-zatarra": [
    52.371329800000005,
    4.927014799999999
  ],
  "papillon-bakery-cafe-restaurant": [
    52.39663040000001,
    4.906659500000001
  ],
  "papote-cafe": [
    52.369022099999995,
    4.8546613999999995
  ],
  "park-kiosk-amstel": [
    52.332015999999996,
    4.8918051
  ],
  "park-kiosk-bea": [
    52.3435208,
    4.883983
  ],
  "paskamer": [
    52.350815,
    4.897824
  ],
  "patio": [
    52.365038,
    4.8506287
  ],
  "patrick-s-gym": [
    52.3629387,
    4.838133099999999
  ],
  "petit-lou": [
    52.364104999999995,
    4.906586
  ],
  "pina-specialty-coffee-matcha": [
    52.375989399999995,
    4.959647599999999
  ],
  "pipes-beans": [
    52.3491997,
    4.8490893999999996
  ],
  "piqniq": [
    52.3803024,
    4.8860939
  ],
  "plantage-dok": [
    52.3684872,
    4.9111965
  ],
  "playhood": [
    52.396338899999996,
    4.877476
  ],
  "pllek": [
    52.3991581,
    4.8928756
  ],
  "pluk": [
    52.3703059,
    4.8834783
  ],
  "pluk-amsterdam": [
    52.372330299999994,
    4.883761499999999
  ],
  "podieum": [
    52.349356,
    4.8287581
  ],
  "podium-mozaiek": [
    52.380097,
    4.854324
  ],
  "polaberry": [
    52.372428,
    4.882542
  ],
  "pong-ping-pong-bar": [
    52.3717031,
    4.8455848999999995
  ],
  "poolbar-de-gracht": [
    52.3626717,
    4.9097059
  ],
  "popeye-coffeeshop": [
    52.379952200000005,
    4.8928135
  ],
  "priesthood": [
    52.376584,
    4.899513
  ],
  "prins-heerlijk": [
    52.37638,
    4.899858
  ],
  "prix-d-ami": [
    52.3768702,
    4.897145699999999
  ],
  "proeflokaal-vesp": [
    52.3710817,
    4.8533214
  ],
  "pudu-cafe": [
    52.369757899999996,
    4.8496572
  ],
  "qahwa-d-or": [
    52.3634472,
    4.9402935
  ],
  "quinnie-s": [
    52.3422516,
    4.9070368
  ],
  "qv-winebar": [
    52.3482734,
    4.876805399999999
  ],
  "rainbowls-amsterdam": [
    52.3569883,
    4.8885885
  ],
  "ranchi-amsterdam": [
    52.3567541,
    4.8985211
  ],
  "reload-coffee": [
    52.3556369,
    4.8887303
  ],
  "rembrandt-corner": [
    52.369367999999994,
    4.90111
  ],
  "restaurant-cafe-in-de-waag": [
    52.372711499999994,
    4.9004026
  ],
  "restaurant-east": [
    52.349897999999996,
    4.9186931000000005
  ],
  "restaurant-heemelrijck-de-pijp": [
    52.356863999999995,
    4.899983199999999
  ],
  "restaurant-heemelrijck-leidseplein": [
    52.363086599999995,
    4.8845956
  ],
  "restaurant-vooges-aan-t-ij": [
    52.387641900000006,
    4.892586
  ],
  "ride-out-amsterdam": [
    52.343066699999994,
    4.856139499999999
  ],
  "rijksmuseum-cafe": [
    52.35999950000001,
    4.8852307
  ],
  "rise-bakery": [
    52.356055399999995,
    4.8961991
  ],
  "rob-wigboldus-fishmonger": [
    52.374186099999996,
    4.8938745
  ],
  "roberto-s-deli": [
    52.3544342,
    4.8713032
  ],
  "rolling-bean": [
    52.355525099999994,
    4.8477979
  ],
  "rum-baba": [
    52.3691337,
    4.8787234
  ],
  "rum-baba-coffeeroasters-shop-brew-bar-east": [
    52.355993600000005,
    4.9265403
  ],
  "rum-barrel": [
    52.3882255,
    4.8800355
  ],
  "saakouk": [
    52.358719099999995,
    4.8056683
  ],
  "saffraan": [
    52.3554566,
    4.9076523
  ],
  "sagra-food-wine": [
    52.3659238,
    4.911579199999999
  ],
  "saint-jean": [
    52.3803056,
    4.884282400000001
  ],
  "salvo": [
    52.3741092,
    4.8744115
  ],
  "salvo-basement": [
    52.3640268,
    4.897867499999999
  ],
  "sam-s-koffie-noord": [
    52.386696799999996,
    4.9236732
  ],
  "sam-s-koffie-west": [
    52.36771170000001,
    4.8660551
  ],
  "samen-lunch-and-juices": [
    52.3826,
    4.8553111
  ],
  "sameplace": [
    52.3740454,
    4.8747378999999995
  ],
  "sandwichshop-amsterdam-damrak": [
    52.3754919,
    4.898245
  ],
  "sandwichshop-amsterdam-rokin": [
    52.3693592,
    4.8930995
  ],
  "sango": [
    52.3785368,
    4.8945098
  ],
  "satellite-sportscafe": [
    52.3640585,
    4.8834947
  ],
  "scandinavian-embassy": [
    52.353456099999995,
    4.8942191
  ],
  "scandinavian-embassy-bakery-shop": [
    52.3421212,
    4.893257
  ],
  "science-cafe": [
    52.3354692,
    4.860619
  ],
  "screaming-beans-utrechtsestraat": [
    52.3633046,
    4.8986994
  ],
  "screaming-beans-waterlooplein": [
    52.3686094,
    4.9021188
  ],
  "selma-s": [
    52.3751971,
    4.8616092
  ],
  "seoul-food": [
    52.366945199999996,
    4.871675
  ],
  "shakerato": [
    52.3628873,
    4.8797697
  ],
  "sham-delights": [
    52.383461200000006,
    4.8855828
  ],
  "shell": [
    52.30023200000001,
    4.9462022
  ],
  "shell-2": [
    52.349638999999996,
    4.885415
  ],
  "shell-3": [
    52.3474265,
    4.926608
  ],
  "shell-4": [
    52.328244,
    4.889635
  ],
  "shell-5": [
    52.30269,
    4.947391
  ],
  "shobiyet-amsterdam-cafe-restaurant": [
    52.357081099999995,
    4.7954633
  ],
  "shot-lifestyle-coffee": [
    52.348410400000006,
    4.8614565
  ],
  "skina": [
    52.3688481,
    4.8713153
  ],
  "small-world-catering": [
    52.382265,
    4.8870355
  ],
  "snackbar-el-hefnawy": [
    52.3514759,
    4.8488004
  ],
  "societeit-ramses-shaffy-huis": [
    52.3754083,
    4.9285543999999994
  ],
  "soil-vegan-cafe": [
    52.368524799999996,
    4.8716456
  ],
  "sol-coffee-bar": [
    52.3537798,
    4.8992785
  ],
  "soupenzo-van-baerle": [
    52.3542882,
    4.8816086
  ],
  "sparekey-bar-cafe": [
    52.3465783,
    4.8473391
  ],
  "stach-food": [
    52.3628539,
    4.8749025
  ],
  "stach-food-2": [
    52.371314999999996,
    4.860088999999999
  ],
  "stach-food-3": [
    52.3615461,
    4.8649381
  ],
  "stach-food-4": [
    52.3525613,
    4.9027629
  ],
  "stach-food-5": [
    52.3441128,
    4.857358
  ],
  "stach-food-6": [
    52.3338225,
    4.8883597
  ],
  "stach-food-haarlemmerstraat": [
    52.3813825,
    4.8896619
  ],
  "stach-x-the-social-hub-amsterdam-west": [
    52.372151699999996,
    4.8360845
  ],
  "stadscafe-ten-westen": [
    52.3834114,
    4.8915600999999995
  ],
  "stadscafe-van-mechelen": [
    52.3527298,
    4.8524728
  ],
  "starbucks": [
    52.374289999999995,
    4.894307
  ],
  "starbucks-10": [
    52.312174899999995,
    4.947705
  ],
  "starbucks-11": [
    52.346553899999996,
    4.918449799999999
  ],
  "starbucks-2": [
    52.3661241,
    4.8977843
  ],
  "starbucks-3": [
    52.3645496,
    4.8836333
  ],
  "starbucks-4": [
    52.3798957,
    4.9005785
  ],
  "starbucks-5": [
    52.3784104,
    4.9006577
  ],
  "starbucks-6": [
    52.366998,
    4.889669
  ],
  "starbucks-7": [
    52.3892232,
    4.8375534
  ],
  "starbucks-8": [
    52.339618699999995,
    4.873124799999999
  ],
  "starbucks-9": [
    52.370312,
    4.892250499999999
  ],
  "staring-at-jacob": [
    52.36231,
    4.861847099999999
  ],
  "stefs-bakery": [
    52.363271499999996,
    4.888440699999999
  ],
  "stichting-de-gibraltar": [
    52.384733999999995,
    4.8484229999999995
  ],
  "stichting-de-ossestal": [
    52.362812,
    4.7990815
  ],
  "sticky-fingers": [
    52.3572322,
    4.8553535
  ],
  "stone-s-cafe-bar-nightclub": [
    52.374579600000004,
    4.8967642
  ],
  "straat-cafe": [
    52.401843199999995,
    4.894199599999999
  ],
  "strain-hunters-coffeeshop": [
    52.368757699999996,
    4.8882696999999995
  ],
  "stretch-and-fold": [
    52.396558899999995,
    4.9074992
  ],
  "stroopist": [
    52.3736381,
    4.8957822
  ],
  "subcult": [
    52.3841191,
    4.9132009
  ],
  "superskunk-coffeeshop": [
    52.364258799999995,
    4.885154600000001
  ],
  "t-blaauwhooft": [
    52.3837666,
    4.8888972
  ],
  "t-luikje": [
    52.3563657,
    4.8278433
  ],
  "t-s-teabar": [
    52.3325014,
    4.8760059
  ],
  "taal-coffee": [
    52.3600735,
    4.8581158
  ],
  "tabletop-game-cafe-2-klaveren": [
    52.370154799999995,
    4.865567899999999
  ],
  "taigu-de-pijp": [
    52.352433,
    4.889616999999999
  ],
  "tante-toorop-flink": [
    52.3612562,
    4.8368537
  ],
  "tapi-n-bowls": [
    52.352372499999994,
    4.8890782999999995
  ],
  "tapmarin": [
    52.353356,
    4.9023251
  ],
  "tatli-taarten-van-asli": [
    52.358588399999995,
    4.8009442
  ],
  "tazzina": [
    52.3815453,
    4.8860524
  ],
  "tea-kee-bubble-tea-amsterdam": [
    52.361407400000004,
    4.882615299999999
  ],
  "tea-stories-amsterdam": [
    52.3833361,
    4.886173599999999
  ],
  "teds-amsterdam-east-all-day-brunch": [
    52.3569007,
    4.9177956
  ],
  "teds-amsterdam-jordaan-all-day-brunch": [
    52.3742446,
    4.882630499999999
  ],
  "teds-amsterdam-oud-west-all-day-brunch": [
    52.3653,
    4.874789300000001
  ],
  "terras-van-de-nacht": [
    52.3444639,
    4.8360125
  ],
  "terrasmus": [
    52.374103000000005,
    4.850274
  ],
  "tha-dogg-house-a-snoop-dogg-store": [
    52.3727133,
    4.8761101
  ],
  "the-5th-amsterdam-oost": [
    52.365379999999995,
    4.9354587
  ],
  "the-block-coffee": [
    52.33764250000001,
    4.8934371
  ],
  "the-breakfast-club": [
    52.3563924,
    4.9104573
  ],
  "the-breakfast-club-2": [
    52.3886525,
    4.8399373
  ],
  "the-breakfast-club-3": [
    52.38457,
    4.8829245
  ],
  "the-breakfast-club-4": [
    52.336533499999994,
    4.8731034
  ],
  "the-breakfast-club-5": [
    52.3510603,
    4.8911294
  ],
  "the-bulldog-mack": [
    52.3732681,
    4.8971443
  ],
  "the-coffee": [
    52.3643064,
    4.8744765
  ],
  "the-coffee-bridge": [
    52.3648591,
    4.8597711
  ],
  "the-coffee-virus": [
    52.384204999999994,
    4.902947999999999
  ],
  "the-coffeebrand": [
    52.351744800000006,
    4.8499839
  ],
  "the-cottage-shop-deli": [
    52.3566955,
    4.9271025999999996
  ],
  "the-fix-at-clinkmama": [
    52.3697514,
    4.9068399
  ],
  "the-greasy-spoon": [
    52.368189900000004,
    4.8750822
  ],
  "the-greek-embassy-coffee-bar-kouzina": [
    52.352961699999994,
    4.910444399999999
  ],
  "the-greek-embassy-coffee-deli-gyros": [
    52.352273399999994,
    4.8886376
  ],
  "the-happy-pig-pancake-shop": [
    52.3703789,
    4.8892555
  ],
  "the-living-kitchen-rooftop-restaurant-and-bar-by-zoku-amster": [
    52.363947499999995,
    4.9066543000000005
  ],
  "the-magpie": [
    52.3495083,
    4.848912599999999
  ],
  "the-miners-offee-oud-west": [
    52.3673869,
    4.8688386
  ],
  "the-natureroom-cafe": [
    52.370666899999996,
    4.8128465
  ],
  "the-oba-store": [
    52.33651690000001,
    4.8748321
  ],
  "the-papeneiland": [
    52.380462699999995,
    4.8879703999999995
  ],
  "the-plug-coffeeshop": [
    52.375099299999995,
    4.8916121
  ],
  "the-plug-westerdok": [
    52.389112999999995,
    4.8875755000000005
  ],
  "the-pool-bar": [
    52.3685701,
    4.8906426
  ],
  "the-rookies-coffeeshop": [
    52.362981999999995,
    4.8853089999999995
  ],
  "the-set": [
    52.368686999999994,
    4.953809
  ],
  "the-three-sisters": [
    52.3664248,
    4.897028
  ],
  "the-villy-amsterdam-rhapsody": [
    52.3783306,
    4.8430745
  ],
  "theehuis-de-roos": [
    52.3586214,
    4.8754808
  ],
  "thuis-aan-de-amstel": [
    52.3395222,
    4.9148999
  ],
  "thull-s-deli": [
    52.3728528,
    4.9386754999999996
  ],
  "tjin-s": [
    52.356958,
    4.899836
  ],
  "toastable": [
    52.3673553,
    4.890312199999999
  ],
  "toastable-nieuwendijk": [
    52.3787714,
    4.894698399999999
  ],
  "toasty-lunchroom": [
    52.3588368,
    4.860301199999999
  ],
  "toki": [
    52.3829109,
    4.885517500000001
  ],
  "tolbar": [
    52.3527291,
    4.906675700000001
  ],
  "tolhuistuin": [
    52.3831832,
    4.9032097
  ],
  "trakteren": [
    52.3626072,
    4.8642517
  ],
  "tyson-2-0-coffeeshop-nieuwmarkt": [
    52.372849,
    4.899859
  ],
  "uncommon-bar": [
    52.3631612,
    4.8746955
  ],
  "uncommon-cafe": [
    52.3632851,
    4.8751823
  ],
  "underground-sportclub-amsterdam": [
    52.363907,
    4.9036789999999995
  ],
  "vanaut": [
    52.3641188,
    4.8556174
  ],
  "vascobelo-v-bar-noma-house": [
    52.3368569,
    4.8682662
  ],
  "vascobelo-v-bar-rijnstraat": [
    52.3438133,
    4.9064839
  ],
  "vascobelo-v-bar-stadionplein": [
    52.3444444,
    4.8580556
  ],
  "vascobelo-v-point-eurocenter": [
    52.3358406,
    4.8892961999999995
  ],
  "velvet-square-cafe": [
    52.3893997,
    4.9036069
  ],
  "venetie-ijs": [
    52.3457325,
    4.8906925999999995
  ],
  "venster-33": [
    52.3564206,
    4.8923475
  ],
  "vergulden-eenhoorn": [
    52.3510419,
    4.9207366
  ],
  "viet-drip-coffee": [
    52.360406999999995,
    4.9184237
  ],
  "villa-break": [
    52.3123332,
    4.9385753
  ],
  "villa-tante-bep": [
    52.3051463,
    5.016181
  ],
  "vin-noord": [
    52.3912883,
    4.9447953
  ],
  "vinnies": [
    52.3461254,
    4.8913307
  ],
  "vintarista": [
    52.3845725,
    4.8736961999999995
  ],
  "vlaamsch-broodhuys-amstelveenseweg-amsterdam": [
    52.3527473,
    4.855923199999999
  ],
  "vlaamsch-broodhuys-eerste-constantijn-huygensstraat-amsterda": [
    52.3639253,
    4.8742139
  ],
  "vlaamsch-broodhuys-elandsgracht-amsterdam": [
    52.3692983,
    4.8790251
  ],
  "vlaamsch-broodhuys-middenweg-amsterdam": [
    52.3544177,
    4.9297775
  ],
  "vlaamsch-broodhuys-stadionplein-amsterdam": [
    52.344281099999996,
    4.857255299999999
  ],
  "vlaamsch-broodhuys-vijzelstraat-amsterdam": [
    52.3630217,
    4.8922747
  ],
  "volkshotel": [
    52.353840899999994,
    4.911496
  ],
  "wakuli-coffee-amstelveenseweg": [
    52.351508499999994,
    4.8559569
  ],
  "wakuli-coffee-haarlemmerplein": [
    52.384686599999995,
    4.8824398
  ],
  "wakuli-coffee-jan-pieter-heijestraat": [
    52.364155499999995,
    4.8629123
  ],
  "wakuli-coffee-linnaeusstraat": [
    52.3559863,
    4.9280085
  ],
  "wakuli-coffee-vijzelgracht": [
    52.3608019,
    4.8914608
  ],
  "wakuli-coffee-wagenaarstraat": [
    52.3630664,
    4.9269935
  ],
  "wanakam": [
    52.3570743,
    4.909155999999999
  ],
  "wandu-amsterdam": [
    52.3709293,
    4.8796324
  ],
  "werkplaats": [
    52.3535816,
    4.9120349
  ],
  "westcord-art-hotel-amsterdam": [
    52.3926854,
    4.8689265
  ],
  "westerperk-coffee-shop": [
    52.3786067,
    4.8740747
  ],
  "westweelde-het-restaurant": [
    52.386996499999995,
    4.8699072999999995
  ],
  "white-label-coffee": [
    52.370430999999996,
    4.851578
  ],
  "white-label-coffee-north": [
    52.412772,
    4.8907644999999995
  ],
  "winkel-43": [
    52.3790944,
    4.8862844999999995
  ],
  "woof-me": [
    52.353155099999995,
    4.8990347000000005
  ],
  "xtracold-icebar-amsterdam": [
    52.3664368,
    4.8999302
  ],
  "ynk-coffee": [
    52.3583248,
    4.8569078999999995
  ],
  "yoga-den": [
    52.351074499999996,
    4.8545089
  ],
  "your-daily-august": [
    52.3633989,
    4.8393197
  ],
  "your-daily-cruquius": [
    52.36970410000001,
    4.9552664
  ],
  "your-daily-domus": [
    52.3939296,
    4.8740675
  ],
  "yusu": [
    52.3598821,
    4.9110865
  ],
  "zizou-coffee": [
    52.3704985,
    4.8645612
  ],
  "zuivere-koffie-amsterdam": [
    52.355564699999995,
    4.8409045
  ]
};
